/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author sartriaardianthauno
 */
public class showTransaksi extends javax.swing.JFrame {
    private int idShow;
    /**
     * Creates new form showTransaksi
     */
    public showTransaksi() {
        initComponents();
        // Initialize idShow to some default value, or leave it as-is based on your logic
        this.idShow = -1;
        showTransaksi(idShow);
    }

    public showTransaksi(int idShow) {
        this.idShow = idShow;
        initComponents();
        showTransaksi(idShow);
        txt_alamat.setEditable(false);
//        txt_noTransaksi.setText("lol");
//        txt_pegawai.setText("lol");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_pelanggan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_noHp = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_batasWaktu = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_statusPemabayaran = new javax.swing.JLabel();
        txt_dibayarSecara = new javax.swing.JLabel();
        txt_grandTotal = new javax.swing.JLabel();
        txt_biayaTambahan = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JLabel();
        txt_totalPembayaran = new javax.swing.JLabel();
        txt_pembayaran = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_noTransaksi = new javax.swing.JLabel();
        txt_statusLaundry = new javax.swing.JLabel();
        txt_pegawai = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(5, 57, 107));
        jPanel1.setForeground(new java.awt.Color(5, 57, 107));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Show Transaksi");

        kembali.setBackground(new java.awt.Color(255, 153, 51));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembali)
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_pelanggan.setText("jLabel3");

        jLabel12.setText("Pembayaran");

        jLabel2.setText("Nama");

        jLabel11.setText("Total Pembayaran");

        jLabel10.setText("Diskon");

        jLabel9.setText("Biaya tambahan");

        jLabel8.setText("Grand Total");

        jLabel6.setText("Alamat Pengiriman");

        txt_noHp.setText("jLabel3");

        jLabel14.setText("Kembalian");

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "no", "Produk", "Jenis", "Jumlah", "Harga", "Tambahan", "Diskon", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(tableDetail);

        jLabel4.setText("Nomor HP");

        jPanel3.setBackground(new java.awt.Color(5, 57, 107));
        jPanel3.setForeground(new java.awt.Color(5, 57, 107));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Pelanggan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(5, 57, 107));
        jPanel4.setForeground(new java.awt.Color(5, 57, 107));

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Detail Transaksi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel17.setText("Tengat Waktu");

        txt_batasWaktu.setText("jLabel3");

        jLabel20.setText("Dibayar Secara");

        jLabel21.setText("No Transaksi");

        jLabel22.setText("Pegawai yang bertagung jawab :");

        jLabel23.setText("Status Pembayaran");

        txt_statusPemabayaran.setText("jLabel3");

        txt_dibayarSecara.setText("jLabel3");

        txt_grandTotal.setText("jLabel3");

        txt_biayaTambahan.setText("jLabel3");

        txt_diskon.setText("jLabel3");

        txt_totalPembayaran.setText("jLabel3");

        txt_pembayaran.setText("jLabel3");

        txt_kembalian.setText("jLabel3");

        jLabel26.setText("Status Laundry");

        jLabel16.setText(":");

        jLabel19.setText(":");

        jLabel36.setText(":");

        jLabel37.setText(":");

        jLabel38.setText(":");

        jLabel39.setText(":");

        jLabel41.setText(":");

        jLabel42.setText(":");

        jLabel43.setText(":");

        jLabel44.setText(":");

        jLabel45.setText(":");

        jLabel46.setText(":");

        jLabel47.setText(":");

        jLabel48.setText(":");

        txt_noTransaksi.setText("jLabel3");

        txt_statusLaundry.setText("jLabel5");

        txt_pegawai.setText("jLabel3");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane2.setViewportView(txt_alamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_statusPemabayaran)
                                            .addComponent(txt_biayaTambahan)
                                            .addComponent(txt_diskon)))
                                    .addComponent(txt_kembalian)
                                    .addComponent(txt_pembayaran)
                                    .addComponent(txt_totalPembayaran)
                                    .addComponent(txt_dibayarSecara)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_grandTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_pelanggan)
                                                .addComponent(txt_noHp)))
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_statusLaundry))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_noTransaksi)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_batasWaktu))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_pegawai)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel16)
                    .addComponent(txt_noTransaksi)
                    .addComponent(jLabel22)
                    .addComponent(txt_pegawai))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel19)
                    .addComponent(txt_statusLaundry)
                    .addComponent(jLabel17)
                    .addComponent(txt_batasWaktu)
                    .addComponent(jLabel36))
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_pelanggan)
                            .addComponent(jLabel6)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_noHp)
                            .addComponent(jLabel39)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_statusPemabayaran)
                    .addComponent(jLabel41))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel42)
                            .addComponent(txt_dibayarSecara))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel43)
                            .addComponent(txt_grandTotal))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel44))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel45))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel46)
                            .addComponent(txt_totalPembayaran))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel47)
                            .addComponent(txt_pembayaran))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel48)
                            .addComponent(txt_kembalian)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_biayaTambahan)
                        .addGap(15, 15, 15)
                        .addComponent(txt_diskon)))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showTransaksi().setVisible(true);
            }
        });
    }
    
    private ArrayList<Vector<Object>> data = new ArrayList<>();
    
    private void showTransaksi(int showTransaksi) {
        
//        Map<String, Object> dataMap = new HashMap<>();
        
        if (idShow != -1) { // Assuming -1 indicates no valid idEdit
            try {
                String idPelanggan = getPelangganID(idShow) ;
                // Fetch existing data from the database based on idEdit
                String fetchPelangganQuery = "SELECT nama, no_hp FROM pelanggan WHERE id_pelanggan =?";
                java.sql.Connection conn = (Connection) koneksi.configDB();
                try (PreparedStatement pstFetchPelanggan = conn.prepareStatement(fetchPelangganQuery)) {
                     pstFetchPelanggan.setInt(1, Integer.parseInt(idPelanggan));
                    try (ResultSet rsPelanggan = pstFetchPelanggan.executeQuery()) {
                        if (rsPelanggan.next()) {
                            // Set the existing data in your text inputs
                            txt_pelanggan.setText(rsPelanggan.getString("nama"));
                            txt_noHp.setText(String.valueOf(rsPelanggan.getInt("no_hp")));
                        }
                    }
                }

                // Fetch existing data from the transaksi table
                String fetchTransaksiQuery = "SELECT * FROM transaksi WHERE no_transaksi=?";
                try (PreparedStatement pstFetchTransaksi = conn.prepareStatement(fetchTransaksiQuery)) {
                    pstFetchTransaksi.setInt(1, idShow);
                    try (ResultSet rsTransaksi = pstFetchTransaksi.executeQuery()) {
                        if (rsTransaksi.next()) {
                            // Set the existing data in your combo boxes and other UI components
                            
                            txt_noTransaksi.setText(rsTransaksi.getString("no_transaksi"));
                            txt_dibayarSecara.setText(rsTransaksi.getString("dibayar_secara"));
                            String alamat = rsTransaksi.getString("alamat_pengiriman");
                            System.out.println("alamat: "+ alamat);
                            txt_alamat.setText(rsTransaksi.getString("alamat_pengiriman"));
                            
                            String pegawai= getNamaPegawai(rsTransaksi.getString("id_pegawai"));
                            System.out.println("pegawai: "+ pegawai);
                            txt_pegawai.setText(pegawai);
                             // perbaikan
                             
                            int status = rsTransaksi.getInt("status_laundry");
                            String statusText;

                            if (status == 0) {
                                statusText = "baru";
                            } else if (status == 1) {
                                statusText = "prosses";
                            } else if (status == 2) {
                                statusText = "Penjadwalan";
                            } else if (status == 3) {
                                statusText = "Selesai";
                            } else {
                                statusText = "Sudah Lewat";
                            }
                            
                            txt_statusLaundry.setText(statusText);
                            
                            
                            txt_statusPemabayaran.setText(rsTransaksi.getString("status_pembayaran"));
                    
                            txt_grandTotal.setText(rsTransaksi.getString("grandTotal"));
                            txt_biayaTambahan.setText(rsTransaksi.getString("biayaTambahan"));
                            txt_diskon.setText(rsTransaksi.getString("diskon"));
                            txt_totalPembayaran.setText(rsTransaksi.getString("totalPembayaran"));
                            txt_pembayaran.setText(rsTransaksi.getString("pembayaran"));
                            txt_kembalian.setText(rsTransaksi.getString("kembalian"));
//                            txt_tgl.setValue(rsTransaksi.getDate("tanggal_masuk"));
                            txt_batasWaktu.setText(rsTransaksi.getString("batas_waktu"));
                        }
                    }
                }

                    // Fetch existing data from the detail_transaksi table
                    String fetchDetailTransaksiQuery = "SELECT * FROM detail_transaksi WHERE no_transaksi=?";
                    try (PreparedStatement pstFetchDetailTransaksi = conn.prepareStatement(fetchDetailTransaksiQuery)) {
                        pstFetchDetailTransaksi.setInt(1, idShow);
                        try (ResultSet rsDetailTransaksi = pstFetchDetailTransaksi.executeQuery()) {
                            // Clear existing data in your data vector
                            data.clear();

                            while (rsDetailTransaksi.next()) {
                                // Retrieve id_produk from the current row
                                int idProduk = rsDetailTransaksi.getInt("id_produk");

                                // Fetch additional details from the 'produk' table based on id_produk
                                String fetchProdukDetailsQuery = "SELECT nama_produk, jenis_produk FROM produk WHERE id_produk=?";
                                try (PreparedStatement pstFetchProdukDetails = conn.prepareStatement(fetchProdukDetailsQuery)) {
                                    pstFetchProdukDetails.setInt(1, idProduk);
                                    try (ResultSet rsProdukDetails = pstFetchProdukDetails.executeQuery()) {
                                        int detailId = tableDetail.getRowCount() + 1;
                                        
                                        if (rsProdukDetails.next()) {
                                            // Change the logic to retrieve actual data from the result set
                                            String jenisProduk = rsProdukDetails.getString("jenis_produk");
                                            String productName = rsProdukDetails.getString("nama_produk");

                                            // Populate your data vector with existing data and additional details
                                            Vector<Object> row = new Vector<>();
                                            row.add(rsDetailTransaksi.getInt("detailId"));
                                            row.add(productName);
                                            row.add(jenisProduk);
                                            row.add(rsDetailTransaksi.getInt("jumlah"));
                                            row.add(rsDetailTransaksi.getInt("harga"));
                                            row.add(rsDetailTransaksi.getInt("biayaTambahan"));
                                            row.add(rsDetailTransaksi.getInt("diskon"));
                                            row.add(rsDetailTransaksi.getInt("totalHarga"));
                                            // Add the row vector to your data vector
                                            data.add(row);
                                        }
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace(); // Handle SQLException appropriately
                    }

                // Update your UI components with the refreshed data
                // For example, update your JTable if you are using one
                DefaultTableModel tableModel = (DefaultTableModel) tableDetail.getModel();
                tableModel.setRowCount(0); // Clear existing data in the table
                for (Vector<Object> row : data) {
                    tableModel.addRow(row); // Add each row from the refreshed data
                }
                // Notify the table that the data has changed
                tableModel.fireTableDataChanged();
            } catch (Exception e) {
                e.printStackTrace(); 
            }
        }
    }
    
    private String getPelangganID(Integer idTransaksi) {
        try {
            if (idTransaksi != null) {
                String sql = "SELECT id_pelanggan FROM `transaksi` WHERE no_transaksi = ?";
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setInt(1, idTransaksi);

                java.sql.ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    return rs.getString("id_pelanggan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return null;
    }
    
    // Method to get the name of pegawai based on id_pegawai
    private String getNamaPegawai(String idPegawai) {
        // Execute a query to fetch the name based on id_pegawai
        // Replace 'pegawai' with your actual table name
        String query = "SELECT Username FROM user WHERE id_pegawai = ?";
        try {
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, idPegawai);
            java.sql.ResultSet res = pst.executeQuery();
            if (res.next()) {
                return res.getString("Username");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error fetching pegawai name: " + e.getMessage());
        }
        return "";
    }
    
//    private void memberFind(){
//        String query = "SELECT Username FROM user WHERE id_pegawai = ?";
//        try {
//            java.sql.Connection conn = (Connection) koneksi.configDB();
//            java.sql.PreparedStatement pst = conn.prepareStatement(query);
//            pst.setString(1, idPegawai);
//            java.sql.ResultSet res = pst.executeQuery();
//            if (res.next()) {
//                return res.getString("Username");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(null, "Error fetching pegawai name: " + e.getMessage());
//        }
//        return "";
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JLabel txt_batasWaktu;
    private javax.swing.JLabel txt_biayaTambahan;
    private javax.swing.JLabel txt_dibayarSecara;
    private javax.swing.JLabel txt_diskon;
    private javax.swing.JLabel txt_grandTotal;
    private javax.swing.JLabel txt_kembalian;
    private javax.swing.JLabel txt_noHp;
    private javax.swing.JLabel txt_noTransaksi;
    private javax.swing.JLabel txt_pegawai;
    private javax.swing.JLabel txt_pelanggan;
    private javax.swing.JLabel txt_pembayaran;
    private javax.swing.JLabel txt_statusLaundry;
    private javax.swing.JLabel txt_statusPemabayaran;
    private javax.swing.JLabel txt_totalPembayaran;
    // End of variables declaration//GEN-END:variables
}
